### ISSUE TITLE
Issue with interrupted screenshot

### ISSUE THREAD

**Issue by danielballan** [Olog/pyOlog#5]
An issue was reported on the repository for our data collection framework at NSLS-II that is really a pyOlog issue. I'm cross-posting here in case anyone is interested in addressing it. Thanks for your work on this useful project!

cc @ambarb

https://github.com/NSLS-II/bluesky/issues/310

**Comment by berryma4** [comment]
@shroffk, is the issue that a CTRL-C doesn't exit without an error?  Or, a partial entry is made?

**Comment by tacaswell** [comment]
On a bit more inspection, this looks like an issue in NSLS-II grown code that never got pushed upstream.

https://github.com/NSLS-II/pyOlog/pull/1 is the fix for this issue.  Once that PR is merged on ourside I will open a big PR moving all of the ipython/cli code upstream.

**Comment by tacaswell** [comment]
https://github.com/Olog/pyOlog/pull/6 for reference,
